export const BRAND = {
  name: "TCC",
  fullName: "The Creator Connect",
  tagline: "WHERE BRANDS MEET INFLUENCE.",
  description:
    "TCC helps brands scale through creator-led marketing powered by AI systems, analytics, and performance-driven campaigns.",
  email: "hello@thecreatorconnect.com",
  phone: "+91 98765 43210",
  whatsapp: "+919876543210",
  address: "Mumbai, Maharashtra, India",
  socials: {
    instagram: "https://instagram.com/thecreatorconnect",
    twitter: "https://twitter.com/thecreatorconnect",
    linkedin: "https://linkedin.com/company/thecreatorconnect",
    youtube: "https://youtube.com/@thecreatorconnect",
  },
};

export const NAV_LINKS = [
  { label: "Services", href: "/services" },
  { label: "Creators", href: "/creators" },
  { label: "Case Studies", href: "/case-studies" },
  { label: "Blog", href: "/blog" },
  { label: "About", href: "/about" },
  { label: "Pricing", href: "/pricing" },
  { label: "Contact", href: "/contact" },
];

export const SERVICES = [
  {
    id: "influencer-marketing",
    icon: "Users",
    title: "Influencer Marketing",
    description:
      "Connect your brand with the perfect creators to amplify reach, drive authentic engagement, and generate measurable ROI.",
    features: ["Creator matching", "Campaign strategy", "Performance tracking"],
    color: "#dc2626",
  },
  {
    id: "creator-campaigns",
    icon: "Zap",
    title: "Creator Campaigns",
    description:
      "End-to-end campaign management from concept to execution with real-time analytics and optimization.",
    features: ["Campaign design", "Content briefs", "A/B testing"],
    color: "#b91c1c",
  },
  {
    id: "ugc-production",
    icon: "Video",
    title: "UGC Production",
    description:
      "High-converting user-generated content produced by our vetted creator network for ads, social, and e-commerce.",
    features: ["Script writing", "Creator coordination", "Ad-ready content"],
    color: "#991b1b",
  },
  {
    id: "instagram-growth",
    icon: "TrendingUp",
    title: "Instagram Growth",
    description:
      "Data-driven Instagram growth systems combining organic strategy, creator collabs, and paid amplification.",
    features: ["Profile audit", "Content strategy", "Engagement growth"],
    color: "#dc2626",
  },
  {
    id: "ai-content-systems",
    icon: "Brain",
    title: "AI Content Systems",
    description:
      "Proprietary AI tools that automate content ideation, scheduling, performance analysis, and campaign optimization.",
    features: ["AI content briefs", "Automated reports", "Predictive analytics"],
    color: "#b91c1c",
  },
  {
    id: "brand-collaborations",
    icon: "Handshake",
    title: "Brand Collaborations",
    description:
      "Strategic brand-to-creator partnerships that build long-term equity and drive sustained revenue growth.",
    features: ["Brand matching", "Deal negotiation", "Contract management"],
    color: "#991b1b",
  },
  {
    id: "paid-ads",
    icon: "Target",
    title: "Paid Ads",
    description:
      "Performance-driven paid advertising using creator content across Meta, Google, and TikTok ecosystems.",
    features: ["Creative testing", "Audience targeting", "ROAS optimization"],
    color: "#dc2626",
  },
  {
    id: "creator-management",
    icon: "Star",
    title: "Creator Management",
    description:
      "Full-service talent management for creators including brand deals, content strategy, and monetization.",
    features: ["Talent development", "Brand deals", "Revenue scaling"],
    color: "#b91c1c",
  },
  {
    id: "analytics-tracking",
    icon: "BarChart3",
    title: "Analytics & Tracking",
    description:
      "Real-time campaign dashboards with deep insights into reach, engagement, conversions, and revenue attribution.",
    features: ["Custom dashboards", "ROI tracking", "Competitor analysis"],
    color: "#991b1b",
  },
  {
    id: "social-media-strategy",
    icon: "Layers",
    title: "Social Media Strategy",
    description:
      "Comprehensive social media roadmaps that align with your brand goals and drive compounding growth.",
    features: ["Channel strategy", "Content calendar", "Growth roadmap"],
    color: "#dc2626",
  },
];

export const STATS = [
  { value: "500+", label: "Creators Network" },
  { value: "₹50Cr+", label: "Revenue Generated" },
  { value: "200+", label: "Brand Campaigns" },
  { value: "98%", label: "Client Retention" },
];

export const PRICING_PLANS = [
  {
    name: "Starter",
    price: "₹49,999",
    period: "/month",
    description: "Perfect for startups and local businesses entering creator marketing",
    featured: false,
    features: [
      "Up to 5 creator partnerships",
      "1 active campaign",
      "Basic analytics dashboard",
      "UGC content (10 pieces)",
      "Monthly performance report",
      "Email support",
      "Instagram growth strategy",
    ],
    cta: "Get Started",
  },
  {
    name: "Growth",
    price: "₹1,49,999",
    period: "/month",
    description: "Ideal for growing brands ready to scale with creator-led marketing",
    featured: true,
    features: [
      "Up to 25 creator partnerships",
      "5 active campaigns",
      "Advanced analytics & tracking",
      "UGC content (50 pieces)",
      "Weekly performance reports",
      "Dedicated account manager",
      "Paid ads management",
      "AI content systems access",
      "WhatsApp priority support",
      "Brand collaboration deals",
    ],
    cta: "Scale Now",
  },
  {
    name: "Enterprise",
    price: "Custom",
    period: "",
    description: "Full-scale creator ecosystem for established brands and enterprises",
    featured: false,
    features: [
      "Unlimited creator partnerships",
      "Unlimited campaigns",
      "Real-time analytics suite",
      "Unlimited UGC production",
      "Daily performance reports",
      "Dedicated team (3+ members)",
      "Full paid ads management",
      "Custom AI integrations",
      "24/7 priority support",
      "Custom contracts & SLA",
      "White-label reporting",
      "CRM integration",
    ],
    cta: "Contact Us",
  },
];

export const TESTIMONIALS = [
  {
    id: 1,
    name: "Priya Sharma",
    role: "Founder, LuxeBeauty",
    company: "LuxeBeauty",
    image: "/testimonials/priya.jpg",
    rating: 5,
    text: "TCC transformed our brand completely. Within 3 months, our Instagram went from 5K to 85K followers, and our monthly revenue tripled. The creator campaigns they ran were absolutely phenomenal.",
    metrics: { revenue: "+312%", followers: "+1600%", roas: "8.4x" },
  },
  {
    id: 2,
    name: "Arjun Mehta",
    role: "CEO, FitCore India",
    company: "FitCore India",
    image: "/testimonials/arjun.jpg",
    rating: 5,
    text: "The ROI we got from TCC's influencer campaigns was unlike anything we'd experienced before. They connected us with the perfect fitness creators and our supplement line became a category leader.",
    metrics: { revenue: "+245%", followers: "+890%", roas: "6.2x" },
  },
  {
    id: 3,
    name: "Kavya Reddy",
    role: "Marketing Head, StyleVault",
    company: "StyleVault",
    image: "/testimonials/kavya.jpg",
    rating: 5,
    text: "Working with TCC feels like having an entire marketing department. Their AI systems, creator network, and analytics platform are genuinely world-class. Best investment we've made.",
    metrics: { revenue: "+180%", followers: "+2200%", roas: "5.8x" },
  },
  {
    id: 4,
    name: "Rohit Gupta",
    role: "Founder, TechGadgetHub",
    company: "TechGadgetHub",
    image: "/testimonials/rohit.jpg",
    rating: 5,
    text: "TCC's creator-led approach to product launches is next level. Our latest product went viral through their network and we sold out in 48 hours. Absolutely incredible execution.",
    metrics: { revenue: "+420%", followers: "+650%", roas: "11.2x" },
  },
  {
    id: 5,
    name: "Sneha Patel",
    role: "Founder, WellnessFirst",
    company: "WellnessFirst",
    image: "/testimonials/sneha.jpg",
    rating: 5,
    text: "From day one, TCC understood our brand vision and executed campaigns that felt authentic and powerful. Their creator relationships are genuine and that shows in results.",
    metrics: { revenue: "+195%", followers: "+1100%", roas: "7.1x" },
  },
];

export const CASE_STUDIES = [
  {
    id: "luxebeauty-2024",
    brand: "LuxeBeauty",
    category: "Beauty & Skincare",
    duration: "3 months",
    image: "/case-studies/luxebeauty.jpg",
    summary: "Scaled from 5K to 85K followers and 3x revenue in 90 days",
    results: {
      revenue: "+312%",
      followers: "+1600%",
      engagement: "+890%",
      roas: "8.4x",
      leads: "+450%",
    },
    description:
      "Comprehensive creator campaign combining nano-influencers, UGC production, and paid amplification.",
  },
  {
    id: "fitcore-2024",
    brand: "FitCore India",
    category: "Health & Fitness",
    duration: "6 months",
    image: "/case-studies/fitcore.jpg",
    summary: "Became category leader in supplements through 50+ creator partnerships",
    results: {
      revenue: "+245%",
      followers: "+890%",
      engagement: "+720%",
      roas: "6.2x",
      leads: "+380%",
    },
    description:
      "Long-form creator partnership strategy with authentic fitness content and performance tracking.",
  },
  {
    id: "techgadgethub-2024",
    brand: "TechGadgetHub",
    category: "Technology",
    duration: "1 month",
    image: "/case-studies/techgadget.jpg",
    summary: "Product sold out in 48 hours through viral creator launch campaign",
    results: {
      revenue: "+420%",
      followers: "+650%",
      engagement: "+1200%",
      roas: "11.2x",
      leads: "+520%",
    },
    description:
      "High-intensity product launch with tier-1 tech creators and coordinated content drops.",
  },
];

export const CREATORS = [
  {
    id: "aisha-lifestyle",
    name: "Aisha Kapoor",
    category: "Lifestyle",
    followers: "1.2M",
    engagement: "8.4%",
    platforms: ["Instagram", "YouTube"],
    location: "Mumbai",
    avatar: "/creators/aisha.jpg",
    verified: true,
  },
  {
    id: "rahul-fitness",
    name: "Rahul Verma",
    category: "Fitness",
    followers: "890K",
    engagement: "11.2%",
    platforms: ["Instagram", "YouTube"],
    location: "Delhi",
    avatar: "/creators/rahul.jpg",
    verified: true,
  },
  {
    id: "prachi-fashion",
    name: "Prachi Singh",
    category: "Fashion",
    followers: "2.1M",
    engagement: "6.8%",
    platforms: ["Instagram", "TikTok"],
    location: "Bangalore",
    avatar: "/creators/prachi.jpg",
    verified: true,
  },
  {
    id: "dev-tech",
    name: "Dev Malhotra",
    category: "Technology",
    followers: "650K",
    engagement: "9.3%",
    platforms: ["YouTube", "Instagram"],
    location: "Pune",
    avatar: "/creators/dev.jpg",
    verified: true,
  },
  {
    id: "meera-finance",
    name: "Meera Nair",
    category: "Finance",
    followers: "480K",
    engagement: "12.1%",
    platforms: ["Instagram", "LinkedIn"],
    location: "Chennai",
    avatar: "/creators/meera.jpg",
    verified: true,
  },
  {
    id: "karan-food",
    name: "Karan Khanna",
    category: "Food",
    followers: "1.5M",
    engagement: "7.6%",
    platforms: ["YouTube", "Instagram"],
    location: "Mumbai",
    avatar: "/creators/karan.jpg",
    verified: true,
  },
];
