-- Supabase Database Setup for TCC Platform

-- 1. Create leads table
CREATE TABLE public.leads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    company TEXT NOT NULL,
    email TEXT NOT NULL,
    phone TEXT NOT NULL,
    type TEXT NOT NULL,
    budget TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('Hot', 'Warm', 'New', 'Closed')),
    source TEXT NOT NULL,
    time TEXT NOT NULL,
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Create clients table
CREATE TABLE public.clients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    contact TEXT NOT NULL,
    email TEXT NOT NULL,
    phone TEXT NOT NULL,
    plan TEXT NOT NULL CHECK (plan IN ('Starter', 'Growth', 'Enterprise')),
    revenue TEXT NOT NULL,
    campaigns INTEGER NOT NULL DEFAULT 0,
    status TEXT NOT NULL CHECK (status IN ('Active', 'Onboarding', 'Paused')),
    joined TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Create creators table
CREATE TABLE public.creators (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    handle TEXT NOT NULL,
    platform TEXT NOT NULL,
    platforms TEXT[] DEFAULT '{}'::TEXT[],
    followers TEXT NOT NULL,
    category TEXT NOT NULL,
    rate TEXT NOT NULL,
    engagement TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('Active', 'Inactive', 'Pending')),
    rating INTEGER NOT NULL DEFAULT 5,
    campaigns INTEGER NOT NULL DEFAULT 0,
    location TEXT,
    avatar TEXT,
    verified BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Enable Row Level Security (RLS)
ALTER TABLE public.leads ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.clients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.creators ENABLE ROW LEVEL SECURITY;

-- 5. Create basic policies (Allow full access for now since this is an admin dashboard)
-- NOTE: In a true production app with users, you would restrict these policies.
CREATE POLICY "Enable all access for leads" ON public.leads FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all access for clients" ON public.clients FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all access for creators" ON public.creators FOR ALL USING (true) WITH CHECK (true);
